### PR TITLE
doc: fix typos

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by ArminJo** [comment]
Thanks for helping on my english.

**Comment by thijstriemstra** [comment]
@ArminJo you closed the pull request and didn't merge it. Why not? Now my contribution is not recorded at all and it's committed under your name?!

**Comment by ArminJo** [comment]
You are totally right, but I did not want to spend discussions about wrong and missing typos and inconsistent usage.
So it required less time for me.
But thank you very much for improving the repo 🥇

**Comment by thijstriemstra** [comment]
In my 15 years of opensource development I never experienced something like this, incredible.

> So it required less time for me.

I spent time on the contribution and you effectively stole it. I regret helping out.

**Comment by ArminJo** [comment]
Ok I want to be polite, but let et me say it clearer.
You found 2 typos.
You found a better word.
You oversee one typo.
You added one typo.
You changend content you were not asked for.
=> You have to face the fact that your pull request as a whole was useless and offending.

**Comment by thijstriemstra** [comment]
I open pull requests to see how the maintainer(s) respond before I commit to submitting more enhancements. You failed the test. My pull request was offending and useless??? GFY

**Pull request closed without merging**
